-- MySQL Script generated by MySQL Workbench
-- Tue May 21 16:01:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuariosayon` DEFAULT CHARACTER SET utf8 ;
USE `usuariosayon` ;

-- -----------------------------------------------------
-- Table `mydb`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosayon`.`Registro` (
  `Boleta` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Registro` DATE NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Semestre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `FechaLimite` DATE NULL,
  `Envio` INT(1) NULL,
  PRIMARY KEY (`Boleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Casilleros Disponibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosayon`.`CasillerosDisponibles` (
  `Casilleros` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Casilleros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aceptados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosayon`.`Aceptados` (
  `Nombre` VARCHAR(150) NOT NULL,
  `Renovacion` DATE NOT NULL,
  `Boleta` VARCHAR(45) NOT NULL,
  `CasillerosDisponibles` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Boleta`, `CasillerosDisponibles`),
  INDEX `fk_Aceptados_CasillerosDisponibles_idx` (`CasillerosDisponibles` ASC),
  CONSTRAINT `fk_Aceptados_CasillerosDisponibles`
    FOREIGN KEY (`CasillerosDisponibles`)
    REFERENCES `usuariosayon`.`CasillerosDisponibles` (`Casilleros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Renovaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosayon`.`Renovaciones` (
  `Casillero` VARCHAR(20) NOT NULL,
  `Boleta` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Renovacion` DATE NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Casillero`, `Boleta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
